### ISSUE TITLE
Will not work if g:nobin_accept_trailing_dot variable not set

### ISSUE THREAD

**Issue by NlGHT** [Xvezda/vim-nobin#8]
Lines 120-122 mean that the plugin will not work out-of-the-box.
It does a check for whether `g:nobin_accept_trailing_dot` variable is set and I don't see this mentioned in the documentation.  The plugin will not do anything unless this variable has been set.

These lines honestly seem slightly redundant actually.  The global variable doesn't seem to be used in the code anywhere other than here.  I don't know if this is a feature that is being developed, but I haven't been able to have this plugin work because of this (I now realise) for probably a year so.  I almost feel like deleting the lines would just fix it all.  But currently this is a bug or needs to be mentioned in documentation somewhere.
https://github.com/Xvezda/vim-nobin/blob/master/plugin/nobin.vim#L120-L122

**Comment by Xvezda** [comment]
Thank you for point me out. 
Patch for this issue just deployed.

**Comment by NlGHT** [comment]
Awesome!
